name: generate ids

on:
  push:
  workflow_call:
    outputs:
      runId:
        description: "run id"
        value: ${{ jobs.generate-id.outputs.runId }}

jobs:
  generate-id:
    strategy:
      fail-fast: false
      matrix:
        map: [ 'A', 'B' ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate run id
      id: generate-run-id
      run: |
        runId=$(uuidgen)
        echo $runId
        echo "runId=$runId" >> "$GITHUB_OUTPUT"
        if [[ "${{ matrix.map }}" == "A" ]]; then
          exit 1
        fi
    outputs:
      runId: ${{ steps.generate-run-id.outputs.runId }}

  read-outputs:
    runs-on: ubuntu-latest
    needs: [ generate-id ]
    # if: ${{ needs.generate-id.result == 'failure' }}
    steps:
    - name: job output
      run: |
        echo "${{ needs.generate-id.result }}"
        echo "${{ toJSON(needs.generate-id) }}"
