name: generate ids

on:
  push:
  workflow_call:
    outputs:
      runId:
        description: "run id"
        value: ${{ jobs.generate-id.outputs.runId }}

jobs:
  generate-id:
    strategy:
      fail-fast: false
      matrix:
        map: [ 'A', 'B' ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate run id
      id: generate-run-id
      run: |
        runId=$(uuidgen)
        echo $runId
        echo "runId=null" >> "$GITHUB_OUTPUT"

        branch=${{ inputs.branch }}
        repoName=snapstack
        if [[ -z "$branch" ]]
        then
          if [[ ${{ "$repoName" == "snapstack" ]]
          then
            branch=master
          else
            branch=main
          fi
        fi
        echo "branch=branch" >> "$GITHUB_OUTPUT"
    outputs:
      runId: ${{ steps.generate-run-id.outputs.runId }}
      branch: ${{ steps.generate-run-id.outputs.branch }}

  read-outputs:
    runs-on: ubuntu-latest
    needs: [ generate-id ]
    if: ${{ needs.generate-id.outputs.runId == 'null' }}
    steps:
    - name: job output
      run: |
        echo "${{ needs.generate-id.result }}"
        echo "${{ toJSON(needs.generate-id) }}"
