name: "PR Lint"

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - name: Validate PR title
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          message="${{ github.event.pull_request.title }}"
          echo "Analysing title - $message"
          echo $message | commitlint
          echo "PR title looks good!"
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TEST_TOKEN }}
