name: Gem Release Workflow
on: push
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: validate commit format
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js
          message=$(git log -n 1 --pretty=format:'%s')
          echo "Analysing commit - $message"
          echo $message | commitlint
          echo "Git commit looks good!"
          echo "Test auto-merge"

  release-ruby-package:
    runs-on: ubuntu-latest
    needs: [validate-commit-message]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: hola
          version-file: hola.gemspec
          versioning-strategy: always-bump-minor
          token: ${{ secrets.PRIVATE_TEST_TOKEN }}
      - uses: actions/checkout@v2
        with:
          GH_TOKEN: ${{ secrets.PRIVATE_TEST_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

      
      # Setup ruby if a release was created
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
        if: ${{ steps.release.outputs.release_created }}
      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}
      - name: install gh cli
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      # Create and Publish Gem
      - name: publish gem
        run: |
          mkdir -p $HOME/.gem
          echo "release_version=$(gem build *.gemspec | grep Version | awk '{print $NF}')" >> $GITHUB_ENV
          echo "sd_services_commit=$(git rev-parse --short origin/main)" >> $GITHUB_ENV
          pr_number=$(gh pr list -s merged -L 1 --json number -q '.[0].number')
          echo "reviewer_handle=$(gh pr view $pr_number --json reviews -q '.reviews[0].author.login')" >> $GITHUB_ENV
          echo $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TEST_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
