name: generate ids

on:
  push:
  workflow_call:
    outputs:
      runId:
        description: "run id"
        value: ${{ jobs.generate-id.outputs.runId }}

jobs:
  generate-id:
    strategy:
      matrix:
        map: [ 'A', 'B' ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Generate run id
      id: generate-run-id
      run: |
        echo "runId=$RANDOM" >> "$GITHUB_OUTPUT"
    outputs:
      runId: ${{ steps.generate-run-id.outputs.runId }}

  read-outputs:
    runs-on: ubuntu-latest
    needs: [ generate-id ]
    steps:
    - name: job output
      run: echo "${{ toJSON(needs.generate-id) }}"
